version: "3.8"

services:
    chromium:
        image: jacoblincool/chromium-server-cjk
        build:
            context: .
            dockerfile: Dockerfile
            target: chromium
        ports:
            - "53333:53333"
    bot:
        image: jacoblincool/convease
        build:
            context: .
            dockerfile: Dockerfile
            target: bot
        depends_on:
            - chromium
        env_file:
            - .env
