apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - ./kubernetes/bot.yml
    - ./kubernetes/chromium.yml

secretGenerator:
    - name: secret
      behavior: merge
      envs:
          - .env
