name: Image
on:
    push:
        branches:
            - main

jobs:
    image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Login to ghcr
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build CJK Chromium Server
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  target: chromium
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ghcr.io/jacoblincool/chromium-server-cjk:latest

            - name: Build Bot
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  target: bot
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ghcr.io/jacoblincool/convease:latest
